Correctly check exit code

diff --git a/PS1 b/PS1
--- a/PS1
+++ b/PS1
@@ -20,14 +20,15 @@ function parse_git_branch_and_status() {
 
 # Function to determine the prompt color based on the exit status
 function get_exit_status_color() {
-  if [[ $? -eq 0 ]]; then
+  local last_exit_code=$1  # Use the exit code passed to the function
+  if [[ $last_exit_code -eq 0 ]]; then
     printf "${GREEN}✔${RESET}"
   else
     printf "${RED}✘${RESET}"
   fi
 }
 
-# Set the PS1 prompt
-export PS1='$(parse_git_branch_and_status) $(get_exit_status_color) '  # Dynamically add the exit status
+# Set the PS1 prompto
+export PS1='$(get_exit_status_color $?) $(parse_git_branch_and_status) '  # Dynamically add the exit status
 PS1="┌ [\[\033[1;34m\]\u\[\033[0m\]@\[\033[1;34m\]\h\[\033[0m\]:\[\033[1;34m\]\l\[\033[0m\] \[\033[1;33m\]\w\[\033[0m\]] ${PS1}\n└ \$ "
 
